name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSHPASS
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: SSH into the Server
        run: |
          sshpass -p "${{secrets.SSH_PASSWORD}}" ssh -o StrictHostKeyChecking=no ${{secrets.USERNAME}}@${{secrets.HOST}} "echo 'Hello, server!'"
          sshpass -p "${{secrets.SSH_PASSWORD}}" ssh -o StrictHostKeyChecking=no ${{secrets.USERNAME}}@${{secrets.HOST}} "cd tavis-web && git pull"
          sshpass -p "${{secrets.SSH_PASSWORD}}" ssh -o StrictHostKeyChecking=no ${{secrets.USERNAME}}@${{secrets.HOST}} "cd tavis && docker-compose up -d"
          
